using System.Collections;
using System.IO;
using System.Linq;
using System.Threading;
using NUnit.Framework;
using UnityEditor.PackageManager;
using UnityEngine;
using UnityEngine.TestTools;
using Is = UnityEngine.TestTools.Constraints.Is;


namespace PackageTestSuite
{
    public class CleanConsoleTest
    {
        // Make sure it is run before anything else that can affect the console
        [Test, Order(1)]
        public void TestCleanConsole()
        {
            string logs = Utilities.GetLogs();
            // This test is to pick up warnings generated by the Microsoft Roslyn analyzers. However, these may
            // also pick up things from other packages -- which we want to ignore. So only check for log messages
            // specific to the input system here.
			Assert.That(logs, Does.Not.Contain("com.unity.inputsystem"),
                string.Format("Found logs in the console on project startup.\n\nLogs: {0}",logs));
        }
    }
}
