#if (UNITY_STANDALONE || UNITY_EDITOR) && UNITY_ENABLE_STEAMWORKSNET_STEAM_CONTRLLER_SUPPORT

namespace UnityEngine.Experimental.Input.Plugins.Steam
{
    public class SteamworksNETControllerAPI
    {
    }
}

#endif // (UNITY_STANDALONE || UNITY_EDITOR) && UNITY_ENABLE_STEAMWORKSNET_STEAM_CONTROLLER_SUPPORT
