using System;

////REVIEW: this (and the generated C# wrappers) really should be a struct but we can't inherit :/

////TODO: nuke Clone()

namespace UnityEngine.Experimental.Input
{
    /// <summary>
    /// Base class for wrappers generated by the input asset importer.
    /// </summary>
    /// <remarks>
    /// Has a custom property drawer that allows dropping assets onto the
    /// wrapper property.
    /// </remarks>
    [Serializable]
    public class InputActionAssetReference : ICloneable
    {
        /// <summary>
        /// The asset being referenced.
        /// </summary>
        public InputActionAsset asset
        {
            get { return m_Asset; }
            protected set { m_Asset = value; }
        }

        public InputActionAssetReference()
        {
        }

        public InputActionAssetReference(InputActionAsset asset)
        {
            m_Asset = asset;
        }

        public void Enable()
        {
            var sets = asset.actionMaps;
            for (var i = 0; i < sets.Count; ++i)
                sets[i].Enable();
        }

        public void Disable()
        {
            var sets = asset.actionMaps;
            for (var i = 0; i < sets.Count; ++i)
                sets[i].Disable();
        }

        public InputActionAssetReference Clone()
        {
            var clone = (InputActionAssetReference)MemberwiseClone();
            return clone;
        }

        object ICloneable.Clone()
        {
            throw new NotImplementedException();
        }

        [SerializeField] private InputActionAsset m_Asset;
    }
}
