//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by DOTS Input Device Code Generator
//     version 1.1.0
//     from DualShock3GamepadHID Layout
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Input;

#pragma warning disable CS0169

namespace Unity.Input
{
    public struct DualShock3GamepadHIDEvent : IInputData
    {
        public enum Id : uint
        {
            Select = 16,
            LeftStickPress = 17,
            RightStickPress = 18,
            Start = 19,
            DpadUp = 20,
            DpadRight = 21,
            DpadDown = 22,
            DpadLeft = 23,
            LeftTriggerButton = 24,
            RightTriggerButton = 25,
            LeftShoulder = 26,
            RightShoulder = 27,
            ButtonNorth = 28,
            ButtonEast = 29,
            ButtonSouth = 30,
            ButtonWest = 31,
            SystemButton = 32,
            TouchpadButton = 33,
            LeftStickX = 48,
            LeftStickY = 56,
            RightStickX = 64,
            RightStickY = 72,
            LeftTrigger = 144,
            RightTrigger = 152,
        }

        private int Padding0;
        private short Padding1;
        public byte LeftStickX;
        public byte LeftStickY;
        public byte RightStickX;
        public byte RightStickY;
        private long Padding2;
        public byte LeftTrigger;
        public byte RightTrigger;

        public unsafe bool Select
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[2] & ((1 << 0) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[2] |= (1 << 0) & 0xFF;
                else
                    ((byte*)thisPtr)[2] &= ~(1 << 0) & 0xFF;
            }
        }

        public unsafe bool LeftStickPress
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[2] & ((1 << 1) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[2] |= (1 << 1) & 0xFF;
                else
                    ((byte*)thisPtr)[2] &= ~(1 << 1) & 0xFF;
            }
        }

        public unsafe bool RightStickPress
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[2] & ((1 << 2) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[2] |= (1 << 2) & 0xFF;
                else
                    ((byte*)thisPtr)[2] &= ~(1 << 2) & 0xFF;
            }
        }

        public unsafe bool Start
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[2] & ((1 << 3) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[2] |= (1 << 3) & 0xFF;
                else
                    ((byte*)thisPtr)[2] &= ~(1 << 3) & 0xFF;
            }
        }

        public unsafe bool DpadUp
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[2] & ((1 << 4) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[2] |= (1 << 4) & 0xFF;
                else
                    ((byte*)thisPtr)[2] &= ~(1 << 4) & 0xFF;
            }
        }

        public unsafe bool DpadRight
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[2] & ((1 << 5) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[2] |= (1 << 5) & 0xFF;
                else
                    ((byte*)thisPtr)[2] &= ~(1 << 5) & 0xFF;
            }
        }

        public unsafe bool DpadDown
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[2] & ((1 << 6) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[2] |= (1 << 6) & 0xFF;
                else
                    ((byte*)thisPtr)[2] &= ~(1 << 6) & 0xFF;
            }
        }

        public unsafe bool DpadLeft
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[2] & ((1 << 7) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[2] |= (1 << 7) & 0xFF;
                else
                    ((byte*)thisPtr)[2] &= ~(1 << 7) & 0xFF;
            }
        }

        public unsafe bool LeftTriggerButton
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[3] & ((1 << 0) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[3] |= (1 << 0) & 0xFF;
                else
                    ((byte*)thisPtr)[3] &= ~(1 << 0) & 0xFF;
            }
        }

        public unsafe bool RightTriggerButton
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[3] & ((1 << 1) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[3] |= (1 << 1) & 0xFF;
                else
                    ((byte*)thisPtr)[3] &= ~(1 << 1) & 0xFF;
            }
        }

        public unsafe bool LeftShoulder
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[3] & ((1 << 2) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[3] |= (1 << 2) & 0xFF;
                else
                    ((byte*)thisPtr)[3] &= ~(1 << 2) & 0xFF;
            }
        }

        public unsafe bool RightShoulder
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[3] & ((1 << 3) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[3] |= (1 << 3) & 0xFF;
                else
                    ((byte*)thisPtr)[3] &= ~(1 << 3) & 0xFF;
            }
        }

        public unsafe bool ButtonNorth
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[3] & ((1 << 4) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[3] |= (1 << 4) & 0xFF;
                else
                    ((byte*)thisPtr)[3] &= ~(1 << 4) & 0xFF;
            }
        }

        public unsafe bool ButtonEast
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[3] & ((1 << 5) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[3] |= (1 << 5) & 0xFF;
                else
                    ((byte*)thisPtr)[3] &= ~(1 << 5) & 0xFF;
            }
        }

        public unsafe bool ButtonSouth
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[3] & ((1 << 6) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[3] |= (1 << 6) & 0xFF;
                else
                    ((byte*)thisPtr)[3] &= ~(1 << 6) & 0xFF;
            }
        }

        public unsafe bool ButtonWest
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[3] & ((1 << 7) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[3] |= (1 << 7) & 0xFF;
                else
                    ((byte*)thisPtr)[3] &= ~(1 << 7) & 0xFF;
            }
        }

        public unsafe bool SystemButton
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[4] & ((1 << 0) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[4] |= (1 << 0) & 0xFF;
                else
                    ((byte*)thisPtr)[4] &= ~(1 << 0) & 0xFF;
            }
        }

        public unsafe bool TouchpadButton
        {
            get
            {
                fixed(void* thisPtr = &this)
                return (((byte*)thisPtr)[4] & ((1 << 1) & 0xFF)) != 0;
            }
            set
            {
                fixed(void* thisPtr = &this)
                if (value)
                    ((byte*)thisPtr)[4] |= (1 << 1) & 0xFF;
                else
                    ((byte*)thisPtr)[4] &= ~(1 << 1) & 0xFF;
            }
        }

        public uint Format => 2243533099;

        public DOTSInput.InputPipeline InputPipelineParts
        {
            get
            {
                var structMappings = new NativeArray<DOTSInput.InputStructMapping>(kStructMappingCount, Allocator.Persistent);
                var transforms = new NativeArray<DOTSInput.InputTransform>(kTransformCount, Allocator.Persistent);


                // DualShock3GamepadHIDEvent -> DualShock3GamepadHIDInput
                transforms[0] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.Select,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.Select
                };
                transforms[1] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.LeftStickPress,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.LeftStickPress
                };
                transforms[2] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.RightStickPress,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.RightStickPress
                };
                transforms[3] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.Start,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.Start
                };
                transforms[4] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadUp,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.DpadUp
                };
                transforms[5] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadRight,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.DpadRight
                };
                transforms[6] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadDown,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.DpadDown
                };
                transforms[7] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadLeft,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.DpadLeft
                };
                transforms[8] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.LeftTriggerButton,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.LeftTriggerButton
                };
                transforms[9] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.RightTriggerButton,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.RightTriggerButton
                };
                transforms[10] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.LeftShoulder,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.LeftShoulder
                };
                transforms[11] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.RightShoulder,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.RightShoulder
                };
                transforms[12] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonNorth,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.ButtonNorth
                };
                transforms[13] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonEast,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.ButtonEast
                };
                transforms[14] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonSouth,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.ButtonSouth
                };
                transforms[15] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonWest,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.ButtonWest
                };
                transforms[16] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.SystemButton,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.SystemButton
                };
                transforms[17] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.TouchpadButton,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.TouchpadButton
                };
                transforms[18] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.LeftStickX,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.LeftStickX
                };
                transforms[19] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.LeftStickY,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.LeftStickY
                };
                transforms[20] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.RightStickX,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.RightStickX
                };
                transforms[21] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.RightStickY,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.RightStickY
                };
                transforms[22] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToButton),
                    InputId1 = (uint)Id.LeftTrigger,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.LeftTrigger
                };
                transforms[23] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToButton),
                    InputId1 = (uint)Id.RightTrigger,
                    OutputId = (uint)DualShock3GamepadHIDInput.Id.RightTrigger
                };
                structMappings[0] = new DOTSInput.InputStructMapping
                {
                    InputFormat = 2243533099,
                    OutputFormat = 3839365261,
                    InputSizeInBytes = (uint)UnsafeUtility.SizeOf<DualShock3GamepadHIDEvent>(),
                    OutputSizeInBytes = (uint)UnsafeUtility.SizeOf<DualShock3GamepadHIDInput>(),
                    TransformStartIndex = 0,
                    TransformCount = 24
                };

                // DualShock3GamepadHIDEvent -> DualShockGamepadInput
                transforms[24] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.Select,
                    OutputId = (uint)DualShockGamepadInput.Id.Select
                };
                transforms[25] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.LeftStickPress,
                    OutputId = (uint)DualShockGamepadInput.Id.LeftStickPress
                };
                transforms[26] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.RightStickPress,
                    OutputId = (uint)DualShockGamepadInput.Id.RightStickPress
                };
                transforms[27] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.Start,
                    OutputId = (uint)DualShockGamepadInput.Id.Start
                };
                transforms[28] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadUp,
                    OutputId = (uint)DualShockGamepadInput.Id.DpadUp
                };
                transforms[29] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadRight,
                    OutputId = (uint)DualShockGamepadInput.Id.DpadRight
                };
                transforms[30] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadDown,
                    OutputId = (uint)DualShockGamepadInput.Id.DpadDown
                };
                transforms[31] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadLeft,
                    OutputId = (uint)DualShockGamepadInput.Id.DpadLeft
                };
                transforms[32] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.LeftShoulder,
                    OutputId = (uint)DualShockGamepadInput.Id.LeftShoulder
                };
                transforms[33] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.RightShoulder,
                    OutputId = (uint)DualShockGamepadInput.Id.RightShoulder
                };
                transforms[34] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonNorth,
                    OutputId = (uint)DualShockGamepadInput.Id.ButtonNorth
                };
                transforms[35] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonEast,
                    OutputId = (uint)DualShockGamepadInput.Id.ButtonEast
                };
                transforms[36] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonSouth,
                    OutputId = (uint)DualShockGamepadInput.Id.ButtonSouth
                };
                transforms[37] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonWest,
                    OutputId = (uint)DualShockGamepadInput.Id.ButtonWest
                };
                transforms[38] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.TouchpadButton,
                    OutputId = (uint)DualShockGamepadInput.Id.TouchpadButton
                };
                transforms[39] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.LeftStickX,
                    OutputId = (uint)DualShockGamepadInput.Id.LeftStickX
                };
                transforms[40] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.LeftStickY,
                    OutputId = (uint)DualShockGamepadInput.Id.LeftStickY
                };
                transforms[41] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.RightStickX,
                    OutputId = (uint)DualShockGamepadInput.Id.RightStickX
                };
                transforms[42] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.RightStickY,
                    OutputId = (uint)DualShockGamepadInput.Id.RightStickY
                };
                transforms[43] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToButton),
                    InputId1 = (uint)Id.LeftTrigger,
                    OutputId = (uint)DualShockGamepadInput.Id.LeftTrigger
                };
                transforms[44] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToButton),
                    InputId1 = (uint)Id.RightTrigger,
                    OutputId = (uint)DualShockGamepadInput.Id.RightTrigger
                };
                structMappings[1] = new DOTSInput.InputStructMapping
                {
                    InputFormat = 2243533099,
                    OutputFormat = 1290703193,
                    InputSizeInBytes = (uint)UnsafeUtility.SizeOf<DualShock3GamepadHIDEvent>(),
                    OutputSizeInBytes = (uint)UnsafeUtility.SizeOf<DualShockGamepadInput>(),
                    TransformStartIndex = 24,
                    TransformCount = 21
                };

                // DualShock3GamepadHIDEvent -> GamepadInput
                transforms[45] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.Select,
                    OutputId = (uint)GamepadInput.Id.Select
                };
                transforms[46] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.LeftStickPress,
                    OutputId = (uint)GamepadInput.Id.LeftStickPress
                };
                transforms[47] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.RightStickPress,
                    OutputId = (uint)GamepadInput.Id.RightStickPress
                };
                transforms[48] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.Start,
                    OutputId = (uint)GamepadInput.Id.Start
                };
                transforms[49] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadUp,
                    OutputId = (uint)GamepadInput.Id.DpadUp
                };
                transforms[50] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadRight,
                    OutputId = (uint)GamepadInput.Id.DpadRight
                };
                transforms[51] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadDown,
                    OutputId = (uint)GamepadInput.Id.DpadDown
                };
                transforms[52] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.DpadLeft,
                    OutputId = (uint)GamepadInput.Id.DpadLeft
                };
                transforms[53] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.LeftShoulder,
                    OutputId = (uint)GamepadInput.Id.LeftShoulder
                };
                transforms[54] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.RightShoulder,
                    OutputId = (uint)GamepadInput.Id.RightShoulder
                };
                transforms[55] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonNorth,
                    OutputId = (uint)GamepadInput.Id.ButtonNorth
                };
                transforms[56] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonEast,
                    OutputId = (uint)GamepadInput.Id.ButtonEast
                };
                transforms[57] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonSouth,
                    OutputId = (uint)GamepadInput.Id.ButtonSouth
                };
                transforms[58] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.BitToButton),
                    InputId1 = (uint)Id.ButtonWest,
                    OutputId = (uint)GamepadInput.Id.ButtonWest
                };
                transforms[59] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.LeftStickX,
                    OutputId = (uint)GamepadInput.Id.LeftStickX
                };
                transforms[60] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.LeftStickY,
                    OutputId = (uint)GamepadInput.Id.LeftStickY
                };
                transforms[61] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.RightStickX,
                    OutputId = (uint)GamepadInput.Id.RightStickX
                };
                transforms[62] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToAxis),
                    InputId1 = (uint)Id.RightStickY,
                    OutputId = (uint)GamepadInput.Id.RightStickY
                };
                transforms[63] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToButton),
                    InputId1 = (uint)Id.LeftTrigger,
                    OutputId = (uint)GamepadInput.Id.LeftTrigger
                };
                transforms[64] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.ByteToButton),
                    InputId1 = (uint)Id.RightTrigger,
                    OutputId = (uint)GamepadInput.Id.RightTrigger
                };
                structMappings[2] = new DOTSInput.InputStructMapping
                {
                    InputFormat = 2243533099,
                    OutputFormat = 623278190,
                    InputSizeInBytes = (uint)UnsafeUtility.SizeOf<DualShock3GamepadHIDEvent>(),
                    OutputSizeInBytes = (uint)UnsafeUtility.SizeOf<GamepadInput>(),
                    TransformStartIndex = 45,
                    TransformCount = 20
                };

                return new DOTSInput.InputPipeline
                {
                    StructMappings = structMappings,
                    Transforms = transforms,
                };
            }
        }

        private const int kStructMappingCount = 3;
        private const int kTransformCount = 65;
    }

    public struct DualShock3GamepadHIDInput : IComponentData, IInputData
    {
        public Float2Input Dpad;
        public Float2Input LeftStick;
        public Float2Input RightStick;
        public HalfAxisInput LeftTrigger;
        public HalfAxisInput RightTrigger;
        public FloatInput DpadX;
        public FloatInput DpadY;
        public HalfAxisInput LeftStickUp;
        public AxisInput LeftStickX;
        public AxisInput LeftStickY;
        public HalfAxisInput LeftStickDown;
        public HalfAxisInput LeftStickLeft;
        public HalfAxisInput LeftStickRight;
        public HalfAxisInput RightStickUp;
        public AxisInput RightStickX;
        public AxisInput RightStickY;
        public HalfAxisInput RightStickDown;
        public HalfAxisInput RightStickLeft;
        public HalfAxisInput RightStickRight;
        public ButtonInput Select;
        public ButtonInput LeftStickPress;
        public ButtonInput RightStickPress;
        public ButtonInput Start;
        public ButtonInput LeftTriggerButton;
        public ButtonInput RightTriggerButton;
        public ButtonInput LeftShoulder;
        public ButtonInput RightShoulder;
        public ButtonInput ButtonNorth;
        public ButtonInput ButtonEast;
        public ButtonInput ButtonSouth;
        public ButtonInput ButtonWest;
        public ButtonInput SystemButton;
        public ButtonInput TouchpadButton;
        public ButtonInput ButtonLeftTrigger;
        public ButtonInput ButtonRightTrigger;
        public ButtonInput DpadUp;
        public ButtonInput DpadDown;
        public ButtonInput DpadLeft;
        public ButtonInput DpadRight;
        public ButtonInput ButtonLeftStickUp;
        public ButtonInput ButtonLeftStickDown;
        public ButtonInput ButtonLeftStickLeft;
        public ButtonInput ButtonLeftStickRight;
        public ButtonInput ButtonRightStickUp;
        public ButtonInput ButtonRightStickDown;
        public ButtonInput ButtonRightStickLeft;
        public ButtonInput ButtonRightStickRight;

        public enum Id : uint
        {
            Dpad = 0,
            LeftStick = 64,
            RightStick = 128,
            LeftTrigger = 192,
            RightTrigger = 224,
            DpadX = 256,
            DpadY = 288,
            LeftStickUp = 320,
            LeftStickX = 352,
            LeftStickY = 384,
            LeftStickDown = 416,
            LeftStickLeft = 448,
            LeftStickRight = 480,
            RightStickUp = 512,
            RightStickX = 544,
            RightStickY = 576,
            RightStickDown = 608,
            RightStickLeft = 640,
            RightStickRight = 672,
            Select = 704,
            LeftStickPress = 712,
            RightStickPress = 720,
            Start = 728,
            LeftTriggerButton = 736,
            RightTriggerButton = 744,
            LeftShoulder = 752,
            RightShoulder = 760,
            ButtonNorth = 768,
            ButtonEast = 776,
            ButtonSouth = 784,
            ButtonWest = 792,
            SystemButton = 800,
            TouchpadButton = 808,
            ButtonLeftTrigger = 816,
            ButtonRightTrigger = 824,
            DpadUp = 832,
            DpadDown = 840,
            DpadLeft = 848,
            DpadRight = 856,
            ButtonLeftStickUp = 864,
            ButtonLeftStickDown = 872,
            ButtonLeftStickLeft = 880,
            ButtonLeftStickRight = 888,
            ButtonRightStickUp = 896,
            ButtonRightStickDown = 904,
            ButtonRightStickLeft = 912,
            ButtonRightStickRight = 920,
        }
        public uint Format => 3839365261;

        public DOTSInput.InputPipeline InputPipelineParts
        {
            get
            {
                var structMappings = kStructMappingCount > 0 ? new NativeArray<DOTSInput.InputStructMapping>(kStructMappingCount, Allocator.Persistent) : default;
                var transforms = kTransformCount > 0 ? new NativeArray<DOTSInput.InputTransform>(kTransformCount, Allocator.Persistent) : default;

                transforms[0] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Combination.TwoAxesToOneFloat2),
                    InputId1 = (uint)Id.DpadX,
                    InputId2 = (uint)Id.DpadY,
                    OutputId = (uint)Id.Dpad
                };
                transforms[1] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Combination.TwoAxesToOneFloat2),
                    InputId1 = (uint)Id.LeftStickX,
                    InputId2 = (uint)Id.LeftStickY,
                    OutputId = (uint)Id.LeftStick
                };
                transforms[2] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Combination.TwoAxesToOneFloat2),
                    InputId1 = (uint)Id.RightStickX,
                    InputId2 = (uint)Id.RightStickY,
                    OutputId = (uint)Id.RightStick
                };
                transforms[3] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.PositiveAxisToHalfAxis),
                    InputId1 = (uint)Id.LeftStickY,
                    OutputId = (uint)Id.LeftStickUp
                };
                transforms[4] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.HalfAxisToButton),
                    InputId1 = (uint)Id.LeftStickUp,
                    OutputId = (uint)Id.ButtonLeftStickUp
                };
                transforms[5] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.NegativeAxisToHalfAxis),
                    InputId1 = (uint)Id.LeftStickY,
                    OutputId = (uint)Id.LeftStickDown
                };
                transforms[6] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.HalfAxisToButton),
                    InputId1 = (uint)Id.LeftStickDown,
                    OutputId = (uint)Id.ButtonLeftStickDown
                };
                transforms[7] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.NegativeAxisToHalfAxis),
                    InputId1 = (uint)Id.LeftStickX,
                    OutputId = (uint)Id.LeftStickLeft
                };
                transforms[8] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.HalfAxisToButton),
                    InputId1 = (uint)Id.LeftStickLeft,
                    OutputId = (uint)Id.ButtonLeftStickLeft
                };
                transforms[9] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.PositiveAxisToHalfAxis),
                    InputId1 = (uint)Id.LeftStickX,
                    OutputId = (uint)Id.LeftStickRight
                };
                transforms[10] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.HalfAxisToButton),
                    InputId1 = (uint)Id.LeftStickRight,
                    OutputId = (uint)Id.ButtonLeftStickRight
                };
                transforms[11] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.PositiveAxisToHalfAxis),
                    InputId1 = (uint)Id.RightStickY,
                    OutputId = (uint)Id.RightStickUp
                };
                transforms[12] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.HalfAxisToButton),
                    InputId1 = (uint)Id.RightStickUp,
                    OutputId = (uint)Id.ButtonRightStickUp
                };
                transforms[13] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.NegativeAxisToHalfAxis),
                    InputId1 = (uint)Id.RightStickY,
                    OutputId = (uint)Id.RightStickDown
                };
                transforms[14] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.HalfAxisToButton),
                    InputId1 = (uint)Id.RightStickDown,
                    OutputId = (uint)Id.ButtonRightStickDown
                };
                transforms[15] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.NegativeAxisToHalfAxis),
                    InputId1 = (uint)Id.RightStickX,
                    OutputId = (uint)Id.RightStickLeft
                };
                transforms[16] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.HalfAxisToButton),
                    InputId1 = (uint)Id.RightStickLeft,
                    OutputId = (uint)Id.ButtonRightStickLeft
                };
                transforms[17] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.PositiveAxisToHalfAxis),
                    InputId1 = (uint)Id.RightStickX,
                    OutputId = (uint)Id.RightStickRight
                };
                transforms[18] = new DOTSInput.InputTransform
                {
                    Operation = DOTSInput.ToTransformOperation(DOTSInput.Conversion.HalfAxisToButton),
                    InputId1 = (uint)Id.RightStickRight,
                    OutputId = (uint)Id.ButtonRightStickRight
                };

                structMappings[0] = new DOTSInput.InputStructMapping
                {
                    InputFormat = 3839365261,
                    OutputFormat = 3839365261,
                    InputSizeInBytes = (uint)UnsafeUtility.SizeOf<DualShock3GamepadHIDInput>(),
                    OutputSizeInBytes = (uint)UnsafeUtility.SizeOf<DualShock3GamepadHIDInput>(),
                    TransformStartIndex = 0,
                    TransformCount = 19
                };
                return new DOTSInput.InputPipeline
                {
                    StructMappings = structMappings,
                    Transforms = transforms,
                };
            }
        }

        private const int kStructMappingCount = 1;
        private const int kTransformCount = 19;
    }
}
