namespace ISX
{
    // Base class for wrappers generated by the input asset importer.
    // Has a custom property drawer that allows dropping assets onto the
    // wrapper property.
    public class InputActionWrapper
    {
        public InputActionAsset asset { get; set; }

        public void Enable()
        {
            var sets = asset.actionSets;
            for (var i = 0; i < sets.Count; ++i)
                sets[i].Enable();
        }

        public void Disable()
        {
            var sets = asset.actionSets;
            for (var i = 0; i < sets.Count; ++i)
                sets[i].Disable();
        }
    }
}
